/**
 * EventType enum — replaces @shared/events.
 * Contains every event type referenced by the CodeSmith engine.
 */
export const EventType = {
    // Execution lifecycle
    EXECUTION_CREATED: 'EXECUTION_CREATED',
    EXECUTION_COMPLETED: 'EXECUTION_COMPLETED',
    EXECUTION_FAILED: 'EXECUTION_FAILED',
    EXECUTION_ABORTED: 'EXECUTION_ABORTED',
    EXECUTION_REPLAY_STARTED: 'EXECUTION_REPLAY_STARTED',
    EXECUTION_REPLAY_COMPLETED: 'EXECUTION_REPLAY_COMPLETED',

    // Agent lifecycle
    AGENT_STARTED: 'AGENT_STARTED',
    AGENT_COMPLETED: 'AGENT_COMPLETED',
    AGENT_FAILED: 'AGENT_FAILED',

    // File operations
    FILE_UPDATED: 'FILE_UPDATED',
    FILE_WRITTEN: 'FILE_WRITTEN',

    // Command operations
    COMMAND_STARTED: 'COMMAND_STARTED',
    COMMAND_OUTPUT: 'COMMAND_OUTPUT',
    COMMAND_EXITED: 'COMMAND_EXITED',
    COMMAND_EXECUTED: 'COMMAND_EXECUTED',

    // Streaming
    STREAM_TEXT: 'STREAM_TEXT',

    // Workspace
    WORKSPACE_INITIALIZED: 'WORKSPACE_INITIALIZED',
    WORKSPACE_CLEANED: 'WORKSPACE_CLEANED',
    WORKSPACE_CLEANUP_SCHEDULED: 'WORKSPACE_CLEANUP_SCHEDULED',

    // Build & Deploy
    BUILD_ARTIFACT_PERSISTED: 'BUILD_ARTIFACT_PERSISTED',
    ARTIFACT_VERSIONED: 'ARTIFACT_VERSIONED',
    PREVIEW_STATUS: 'PREVIEW_STATUS',
    DEPLOYMENT_STARTED: 'DEPLOYMENT_STARTED',
    DEPLOYMENT_LOG: 'DEPLOYMENT_LOG',
    DEPLOYMENT_COMPLETED: 'DEPLOYMENT_COMPLETED',
    DEPLOYMENT_FAILED: 'DEPLOYMENT_FAILED',
    DEPLOYMENT_ROLLBACK: 'DEPLOYMENT_ROLLBACK',

    // Misc
    ACTION_TIMELINE: 'ACTION_TIMELINE',
    SECURITY_ALERT: 'SECURITY_ALERT',
    TOOL_OPERATION: 'TOOL_OPERATION',
} as const;

export type EventTypeValue = (typeof EventType)[keyof typeof EventType];
